docker run --name postgres-omop -e POSTGRES_PASSWORD=mysecretpassword -p 5432:5432 -d postgres

#create a database
docker exec -it postgres-omop psql -U postgres -c "CREATE DATABASE omop;"

#copy the create table sql file to postgres container
docker cp "$(pwd)/ddl_scripts/ddl.sql" postgres-omop:/ 

#create ddl schema if not already exits, also creates table from ddl.sql
docker exec -it postgres-omop psql -U postgres -d omop -f "/ddl.sql"

#copy  primary key creation sql file to container
docker cp "$(pwd)/ddl_scripts/primary_keys.sql" postgres-omop:/  

#execute the primary key sql file
docker exec -it postgres-omop psql -U postgres -d omop -f "/primary_keys.sql"

#verify the schema
docker exec -it postgres-omop psql -U postgres -d omop -c "\dt cdmDatabaseSchema.*" 

## SPARK

## create a docker network for isolated and secure communication
docker network create etl-network

## running apche spark container connected to etl-network
docker run -it --name spark-master \
  --network etl-network \
  -p 8080:8080 -p 7077:7077 \
  -e SPARK_MODE=master \
  bitnami/spark:latest

# connecting postgres to same etl netwrok
docker network connect etl-network postgres-omop


#copying csv and etl script to spark-container
docker cp etl_scripts/fitbit_to_omop_etl.py spark-master:/opt/bitnami/spark
docker cp etl_scripts/fitbit_data.csv spark-master:/opt/bitnami/spark 


#running the etl script
docker exec -it spark-master spark-submit \
  --master "local[*]" \
  --packages org.postgresql:postgresql:42.2.18 \
  /opt/bitnami/spark/fitbit_to_omop_etl.py